project:
  type: book
  output-dir: docs

book:
  favicon: logo-icon.svg
  google-analytics: "G-RVRBE7Y1R2"
  title: "R for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com
      orcid: 0000-0001-6772-9291
  date: "02/09/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - prepare.qmd
    - clean.qmd
    - viz.qmd
    - references.qmd

execute:
  freeze: auto
  
bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

