project:
  type: book
  output-dir: docs

book:
  favicon: logo-icon.svg
  google-analytics: "G-RDC0B0FCNZ"
  title: "R for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com
      orcid: 0000-0001-6772-9291
  date: "02/09/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - prepare.qmd
    - r_basics.qmd
    - clean.qmd
    - analysis.qmd
    - viz.qmd
    - viz-practice.qmd
    - report.qmd
    - references.qmd

execute:
  freeze: auto
  
bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: [cosmo, theme.scss]
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

comments:
  giscus:
    repo: thinhong/r4babies